#!/sbin/busybox sh
_PATH="$PATH"
export PATH=/sbin

busybox sh /stage1/initbbox.sh

cd /
date >>/tmp/stage1.txt
exec >>/tmp/stage1.txt 2>&1
rm init
mount -t proc proc /proc
mount -t sysfs sysfs /sys

load_image=/stage1/boot.cpio

if grep -q bootmode=2 /proc/cmdline ; then
	# recovery boot
	load_image=/stage1/recovery.cpio
fi

if dmesg | grep S3C-Keypad | grep 102; then
	echo "force normal boot"
	load_image=/stage1/boot.cpio
fi

if dmesg | grep S3C-Keypad | grep 139; then
	echo "force recovery boot"
	load_image=/stage1/recovery.cpio
fi

cpio -i < ${load_image}

mkdir -p /lib/modules
cd /lib/modules/
tar xvf /stage1/modules.tar
cd /

insmod -f /lib/modules/fsr.ko
insmod -f /lib/modules/fsr_stl.ko
insmod -f /lib/modules/rfs_glue.ko
insmod -f /lib/modules/rfs_fat.ko
sh /stage1/fsdetect.sh > /tmp/fsdetect.txt 2> /tmp/fsdetect.txt

umount /sys
umount /proc
date >>/tmp/stage1.txt
rm -fr /stage1 /dev/*
export PATH="${_PATH}"
exec /init

